server.port=8083
spring.application.name=citas-microservicio

# Configuración para Docker
# Cambiamos localhost por 'db' y agregamos la clave 'root'
spring.datasource.url=jdbc:mysql://db:3306/rednorte_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Si usas Feign para conectar con los otros servicios, 
# asegúrate de que las URLs en tus interfaces @FeignClient 
# también usen 'pacientes-ms' y 'medicos-ms' en lugar de localhost.